---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

# Observed Decisions

## Approach Condition

```{r,echo=FALSE}
library(rstan)
library(coda)

hypers=c('w1_mean','w1_sd','w2_mean','w2_sd','w3_mean','w3_sd',
         'delta_a','delta_b','tau_a','tau_b','alpha_a','alpha_b')

load("data/derived/ap_obs_fit.RData")
```

### RStan output

```{r,echo=FALSE}
smrystan = summary(fit)
smrystan[[1]][hypers,]
```

### Coda output

Effective sample size

```{r,echo=FALSE}
stan2coda <- function(fit) {
  mcmc.list(lapply(1:ncol(fit), function(x) mcmc(as.array(fit)[,x,])))
}
effectiveSize(stan2coda(fit))[hypers]
```

Gelman's Rhat

```{r,echo=FALSE}
gelman.diag(stan2coda(fit))[[1]][hypers,]
```

### Plots

```{r,echo=FALSE}
rstan::traceplot(fit,par=hypers)
pairs(fit,pars=hypers)
```

## Avoidance Condition

```{r,echo=FALSE}
load("data/derived/av_obs_fit.RData")
```

### RStan output

```{r,echo=FALSE}
smrystan = summary(fit)
smrystan[[1]][hypers,]
```

### Coda output

Effective sample size
```{r,echo=FALSE}
effectiveSize(stan2coda(fit))[hypers]
```

Gelman's Rhat

```{r,echo=FALSE}
gelman.diag(stan2coda(fit))[[1]][hypers,]
```

### Plots

```{r,echo=FALSE}
rstan::traceplot(fit,par=hypers)
pairs(fit,pars=hypers)
```
