// Code generated by Stan version 2.18.1

#include <stan/model/model_header.hpp>

namespace goal_fixed_space_expt123_bndshape_mpi_model_namespace {

using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;

static int current_statement_begin__;

stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "/QRISdata/Q0993/models/goal_fixed_space_expt123_bndshape_mpi.stan");
    reader.add_event(145, 143, "end", "/QRISdata/Q0993/models/goal_fixed_space_expt123_bndshape_mpi.stan");
    return reader;
}

template <typename T0__, typename T1__, typename T2__>
Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__, T2__>::type, Eigen::Dynamic,1>
goal_sub(const Eigen::Matrix<T0__, Eigen::Dynamic,1>& phi,
             const Eigen::Matrix<T1__, Eigen::Dynamic,1>& theta,
             const std::vector<T2__>& real_data,
             const std::vector<int>& int_data, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 9;
        int Nvalid(0);
        (void) Nvalid;  // dummy to suppress unused var warning

        stan::math::fill(Nvalid, std::numeric_limits<int>::min());
        stan::math::assign(Nvalid,get_base1(int_data,1,"int_data",1));
        current_statement_begin__ = 10;
        int Nplaces(0);
        (void) Nplaces;  // dummy to suppress unused var warning

        stan::math::fill(Nplaces, std::numeric_limits<int>::min());
        stan::math::assign(Nplaces,get_base1(int_data,2,"int_data",1));
        current_statement_begin__ = 14;
        validate_non_negative_index("dat", "3", 3);
        validate_non_negative_index("dat", "Nvalid", Nvalid);
        Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,Eigen::Dynamic>  dat(static_cast<Eigen::VectorXd::Index>(3),static_cast<Eigen::VectorXd::Index>(Nvalid));
        (void) dat;  // dummy to suppress unused var warning

        stan::math::initialize(dat, DUMMY_VAR__);
        stan::math::fill(dat,DUMMY_VAR__);
        current_statement_begin__ = 15;
        validate_non_negative_index("weights", "3", 3);
        Eigen::Matrix<local_scalar_t__,1,Eigen::Dynamic>  weights(static_cast<Eigen::VectorXd::Index>(3));
        (void) weights;  // dummy to suppress unused var warning

        stan::math::initialize(weights, DUMMY_VAR__);
        stan::math::fill(weights,DUMMY_VAR__);
        current_statement_begin__ = 16;
        validate_non_negative_index("p_a_logit", "Nvalid", Nvalid);
        Eigen::Matrix<local_scalar_t__,1,Eigen::Dynamic>  p_a_logit(static_cast<Eigen::VectorXd::Index>(Nvalid));
        (void) p_a_logit;  // dummy to suppress unused var warning

        stan::math::initialize(p_a_logit, DUMMY_VAR__);
        stan::math::fill(p_a_logit,DUMMY_VAR__);
        current_statement_begin__ = 17;
        validate_non_negative_index("y_sub", "Nvalid", Nvalid);
        vector<int> y_sub(Nvalid, 0);
        stan::math::fill(y_sub, std::numeric_limits<int>::min());
        current_statement_begin__ = 20;
        local_scalar_t__ delta_sub;
        (void) delta_sub;  // dummy to suppress unused var warning

        stan::math::initialize(delta_sub, DUMMY_VAR__);
        stan::math::fill(delta_sub,DUMMY_VAR__);
        stan::math::assign(delta_sub,get_base1(theta,4,"theta",1));
        current_statement_begin__ = 21;
        local_scalar_t__ tau_sub;
        (void) tau_sub;  // dummy to suppress unused var warning

        stan::math::initialize(tau_sub, DUMMY_VAR__);
        stan::math::fill(tau_sub,DUMMY_VAR__);
        stan::math::assign(tau_sub,get_base1(theta,5,"theta",1));
        current_statement_begin__ = 22;
        local_scalar_t__ alpha_sub;
        (void) alpha_sub;  // dummy to suppress unused var warning

        stan::math::initialize(alpha_sub, DUMMY_VAR__);
        stan::math::fill(alpha_sub,DUMMY_VAR__);
        stan::math::assign(alpha_sub,get_base1(theta,6,"theta",1));
        current_statement_begin__ = 23;
        local_scalar_t__ one_m_alpha_sub;
        (void) one_m_alpha_sub;  // dummy to suppress unused var warning

        stan::math::initialize(one_m_alpha_sub, DUMMY_VAR__);
        stan::math::fill(one_m_alpha_sub,DUMMY_VAR__);
        stan::math::assign(one_m_alpha_sub,(1 - alpha_sub));
        current_statement_begin__ = 24;
        local_scalar_t__ a_sg;
        (void) a_sg;  // dummy to suppress unused var warning

        stan::math::initialize(a_sg, DUMMY_VAR__);
        stan::math::fill(a_sg,DUMMY_VAR__);
        current_statement_begin__ = 25;
        local_scalar_t__ b_sg;
        (void) b_sg;  // dummy to suppress unused var warning

        stan::math::initialize(b_sg, DUMMY_VAR__);
        stan::math::fill(b_sg,DUMMY_VAR__);
        current_statement_begin__ = 26;
        local_scalar_t__ a_tg;
        (void) a_tg;  // dummy to suppress unused var warning

        stan::math::initialize(a_tg, DUMMY_VAR__);
        stan::math::fill(a_tg,DUMMY_VAR__);
        current_statement_begin__ = 27;
        local_scalar_t__ b_tg;
        (void) b_tg;  // dummy to suppress unused var warning

        stan::math::initialize(b_tg, DUMMY_VAR__);
        stan::math::fill(b_tg,DUMMY_VAR__);
        current_statement_begin__ = 28;
        local_scalar_t__ a_stg_tmp;
        (void) a_stg_tmp;  // dummy to suppress unused var warning

        stan::math::initialize(a_stg_tmp, DUMMY_VAR__);
        stan::math::fill(a_stg_tmp,DUMMY_VAR__);
        current_statement_begin__ = 29;
        local_scalar_t__ b_stg_tmp;
        (void) b_stg_tmp;  // dummy to suppress unused var warning

        stan::math::initialize(b_stg_tmp, DUMMY_VAR__);
        stan::math::fill(b_stg_tmp,DUMMY_VAR__);
        current_statement_begin__ = 30;
        local_scalar_t__ a_stg;
        (void) a_stg;  // dummy to suppress unused var warning

        stan::math::initialize(a_stg, DUMMY_VAR__);
        stan::math::fill(a_stg,DUMMY_VAR__);
        current_statement_begin__ = 31;
        local_scalar_t__ b_stg;
        (void) b_stg;  // dummy to suppress unused var warning

        stan::math::initialize(b_stg, DUMMY_VAR__);
        stan::math::fill(b_stg,DUMMY_VAR__);
        current_statement_begin__ = 34;
        local_scalar_t__ lp;
        (void) lp;  // dummy to suppress unused var warning

        stan::math::initialize(lp, DUMMY_VAR__);
        stan::math::fill(lp,DUMMY_VAR__);


        current_statement_begin__ = 37;
        stan::model::assign(weights, 
                    stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                    get_base1(theta,1,"theta",1), 
                    "assigning variable weights");
        current_statement_begin__ = 38;
        stan::model::assign(weights, 
                    stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()), 
                    get_base1(theta,2,"theta",1), 
                    "assigning variable weights");
        current_statement_begin__ = 39;
        stan::model::assign(weights, 
                    stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list()), 
                    (((get_base1(theta,3,"theta",1) * 2) * one_m_alpha_sub) * stan::math::sqrt((alpha_sub / one_m_alpha_sub))), 
                    "assigning variable weights");
        current_statement_begin__ = 41;
        for (int i = 1; i <= Nvalid; ++i) {

            current_statement_begin__ = 44;
            stan::math::assign(a_sg, stan::math::exp((get_base1(real_data,i,"real_data",1) * delta_sub)));
            current_statement_begin__ = 45;
            stan::math::assign(b_sg, stan::math::exp((get_base1(real_data,(Nplaces + i),"real_data",1) * delta_sub)));
            current_statement_begin__ = 46;
            stan::model::assign(dat, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list())), 
                        (a_sg - b_sg), 
                        "assigning variable dat");
            current_statement_begin__ = 49;
            stan::math::assign(a_tg, stan::math::exp((get_base1(real_data,((2 * Nplaces) + i),"real_data",1) * tau_sub)));
            current_statement_begin__ = 50;
            stan::math::assign(b_tg, stan::math::exp((get_base1(real_data,((3 * Nplaces) + i),"real_data",1) * tau_sub)));
            current_statement_begin__ = 51;
            stan::model::assign(dat, 
                        stan::model::cons_list(stan::model::index_uni(2), stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list())), 
                        (a_tg - b_tg), 
                        "assigning variable dat");
            current_statement_begin__ = 54;
            stan::math::assign(a_stg_tmp, ((alpha_sub * get_base1(real_data,((6 * Nplaces) + i),"real_data",1)) + (one_m_alpha_sub * get_base1(real_data,((4 * Nplaces) + i),"real_data",1))));
            current_statement_begin__ = 55;
            stan::math::assign(b_stg_tmp, ((alpha_sub * get_base1(real_data,((7 * Nplaces) + i),"real_data",1)) + (one_m_alpha_sub * get_base1(real_data,((5 * Nplaces) + i),"real_data",1))));
            current_statement_begin__ = 56;
            stan::math::assign(a_stg, inv(a_stg_tmp));
            current_statement_begin__ = 57;
            stan::math::assign(b_stg, inv(b_stg_tmp));
            current_statement_begin__ = 58;
            stan::model::assign(dat, 
                        stan::model::cons_list(stan::model::index_uni(3), stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list())), 
                        (a_stg - b_stg), 
                        "assigning variable dat");
        }
        current_statement_begin__ = 63;
        stan::math::assign(p_a_logit, multiply(weights,dat));
        current_statement_begin__ = 65;
        stan::math::assign(lp, bernoulli_logit_log(stan::model::rvalue(int_data, stan::model::cons_list(stan::model::index_min_max(3, (Nvalid + 2)), stan::model::nil_index_list()), "int_data"),p_a_logit));
        current_statement_begin__ = 67;
        return stan::math::promote_scalar<fun_return_scalar_t__>(transpose(stan::math::to_row_vector(stan::math::array_builder<local_scalar_t__ >().add(lp).array())));
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}


struct goal_sub_functor__ {
    template <typename T0__, typename T1__, typename T2__>
        Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__, T2__>::type, Eigen::Dynamic,1>
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic,1>& phi,
             const Eigen::Matrix<T1__, Eigen::Dynamic,1>& theta,
             const std::vector<T2__>& real_data,
             const std::vector<int>& int_data, std::ostream* pstream__) const {
        return goal_sub(phi, theta, real_data, int_data, pstream__);
    }
};

class goal_fixed_space_expt123_bndshape_mpi_model : public prob_grad {
private:
    int Ntotal;
    int Nsubj;
    int Max_obs;
    vector<vector<double> > real_data;
    vector<vector<int> > int_data;
    vector<int> expt;
    vector<int> s_sg;
    vector<int> s_tg;
    int Nsubj_sg;
    int Nsubj_tg;
public:
    goal_fixed_space_expt123_bndshape_mpi_model(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }

    goal_fixed_space_expt123_bndshape_mpi_model(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }

    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;

        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning

        current_statement_begin__ = -1;

        static const char* function__ = "goal_fixed_space_expt123_bndshape_mpi_model_namespace::goal_fixed_space_expt123_bndshape_mpi_model";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        // initialize member variables
        try {
            current_statement_begin__ = 72;
            context__.validate_dims("data initialization", "Ntotal", "int", context__.to_vec());
            Ntotal = int(0);
            vals_i__ = context__.vals_i("Ntotal");
            pos__ = 0;
            Ntotal = vals_i__[pos__++];
            current_statement_begin__ = 73;
            context__.validate_dims("data initialization", "Nsubj", "int", context__.to_vec());
            Nsubj = int(0);
            vals_i__ = context__.vals_i("Nsubj");
            pos__ = 0;
            Nsubj = vals_i__[pos__++];
            current_statement_begin__ = 74;
            context__.validate_dims("data initialization", "Max_obs", "int", context__.to_vec());
            Max_obs = int(0);
            vals_i__ = context__.vals_i("Max_obs");
            pos__ = 0;
            Max_obs = vals_i__[pos__++];
            current_statement_begin__ = 75;
            validate_non_negative_index("real_data", "Nsubj", Nsubj);
            validate_non_negative_index("real_data", "(Max_obs * 8)", (Max_obs * 8));
            context__.validate_dims("data initialization", "real_data", "double", context__.to_vec(Nsubj,(Max_obs * 8)));
            validate_non_negative_index("real_data", "Nsubj", Nsubj);
            validate_non_negative_index("real_data", "(Max_obs * 8)", (Max_obs * 8));
            real_data = std::vector<std::vector<double> >(Nsubj,std::vector<double>((Max_obs * 8),double(0)));
            vals_r__ = context__.vals_r("real_data");
            pos__ = 0;
            size_t real_data_limit_1__ = (Max_obs * 8);
            for (size_t i_1__ = 0; i_1__ < real_data_limit_1__; ++i_1__) {
                size_t real_data_limit_0__ = Nsubj;
                for (size_t i_0__ = 0; i_0__ < real_data_limit_0__; ++i_0__) {
                    real_data[i_0__][i_1__] = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 76;
            validate_non_negative_index("int_data", "Nsubj", Nsubj);
            validate_non_negative_index("int_data", "(Max_obs + 2)", (Max_obs + 2));
            context__.validate_dims("data initialization", "int_data", "int", context__.to_vec(Nsubj,(Max_obs + 2)));
            validate_non_negative_index("int_data", "Nsubj", Nsubj);
            validate_non_negative_index("int_data", "(Max_obs + 2)", (Max_obs + 2));
            int_data = std::vector<std::vector<int> >(Nsubj,std::vector<int>((Max_obs + 2),int(0)));
            vals_i__ = context__.vals_i("int_data");
            pos__ = 0;
            size_t int_data_limit_1__ = (Max_obs + 2);
            for (size_t i_1__ = 0; i_1__ < int_data_limit_1__; ++i_1__) {
                size_t int_data_limit_0__ = Nsubj;
                for (size_t i_0__ = 0; i_0__ < int_data_limit_0__; ++i_0__) {
                    int_data[i_0__][i_1__] = vals_i__[pos__++];
                }
            }
            current_statement_begin__ = 77;
            validate_non_negative_index("expt", "Nsubj", Nsubj);
            context__.validate_dims("data initialization", "expt", "int", context__.to_vec(Nsubj));
            validate_non_negative_index("expt", "Nsubj", Nsubj);
            expt = std::vector<int>(Nsubj,int(0));
            vals_i__ = context__.vals_i("expt");
            pos__ = 0;
            size_t expt_limit_0__ = Nsubj;
            for (size_t i_0__ = 0; i_0__ < expt_limit_0__; ++i_0__) {
                expt[i_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 78;
            validate_non_negative_index("s_sg", "Nsubj", Nsubj);
            context__.validate_dims("data initialization", "s_sg", "int", context__.to_vec(Nsubj));
            validate_non_negative_index("s_sg", "Nsubj", Nsubj);
            s_sg = std::vector<int>(Nsubj,int(0));
            vals_i__ = context__.vals_i("s_sg");
            pos__ = 0;
            size_t s_sg_limit_0__ = Nsubj;
            for (size_t i_0__ = 0; i_0__ < s_sg_limit_0__; ++i_0__) {
                s_sg[i_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 79;
            validate_non_negative_index("s_tg", "Nsubj", Nsubj);
            context__.validate_dims("data initialization", "s_tg", "int", context__.to_vec(Nsubj));
            validate_non_negative_index("s_tg", "Nsubj", Nsubj);
            s_tg = std::vector<int>(Nsubj,int(0));
            vals_i__ = context__.vals_i("s_tg");
            pos__ = 0;
            size_t s_tg_limit_0__ = Nsubj;
            for (size_t i_0__ = 0; i_0__ < s_tg_limit_0__; ++i_0__) {
                s_tg[i_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 80;
            context__.validate_dims("data initialization", "Nsubj_sg", "int", context__.to_vec());
            Nsubj_sg = int(0);
            vals_i__ = context__.vals_i("Nsubj_sg");
            pos__ = 0;
            Nsubj_sg = vals_i__[pos__++];
            current_statement_begin__ = 81;
            context__.validate_dims("data initialization", "Nsubj_tg", "int", context__.to_vec());
            Nsubj_tg = int(0);
            vals_i__ = context__.vals_i("Nsubj_tg");
            pos__ = 0;
            Nsubj_tg = vals_i__[pos__++];

            // validate, data variables
            current_statement_begin__ = 72;
            check_greater_or_equal(function__,"Ntotal",Ntotal,0);
            current_statement_begin__ = 73;
            check_greater_or_equal(function__,"Nsubj",Nsubj,0);
            current_statement_begin__ = 74;
            check_greater_or_equal(function__,"Max_obs",Max_obs,0);
            current_statement_begin__ = 75;
            current_statement_begin__ = 76;
            current_statement_begin__ = 77;
            current_statement_begin__ = 78;
            current_statement_begin__ = 79;
            current_statement_begin__ = 80;
            current_statement_begin__ = 81;
            // initialize data variables


            // validate transformed data

            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 86;
            validate_non_negative_index("w1", "Nsubj_sg", Nsubj_sg);
            num_params_r__ += Nsubj_sg;
            current_statement_begin__ = 87;
            validate_non_negative_index("w2", "Nsubj_tg", Nsubj_tg);
            num_params_r__ += Nsubj_tg;
            current_statement_begin__ = 88;
            validate_non_negative_index("w3", "Nsubj", Nsubj);
            num_params_r__ += Nsubj;
            current_statement_begin__ = 89;
            validate_non_negative_index("delta", "Nsubj_sg", Nsubj_sg);
            num_params_r__ += Nsubj_sg;
            current_statement_begin__ = 90;
            validate_non_negative_index("tau", "Nsubj_tg", Nsubj_tg);
            num_params_r__ += Nsubj_tg;
            current_statement_begin__ = 91;
            validate_non_negative_index("alpha", "Nsubj", Nsubj);
            num_params_r__ += Nsubj;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    ~goal_fixed_space_expt123_bndshape_mpi_model() { }


    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        stan::io::writer<double> writer__(params_r__,params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;

        if (!(context__.contains_r("w1")))
            throw std::runtime_error("variable w1 missing");
        vals_r__ = context__.vals_r("w1");
        pos__ = 0U;
        validate_non_negative_index("w1", "Nsubj_sg", Nsubj_sg);
        context__.validate_dims("initialization", "w1", "double", context__.to_vec(Nsubj_sg));
        std::vector<double> w1(Nsubj_sg,double(0));
        for (int i0__ = 0U; i0__ < Nsubj_sg; ++i0__)
            w1[i0__] = vals_r__[pos__++];
        for (int i0__ = 0U; i0__ < Nsubj_sg; ++i0__)
            try {
            writer__.scalar_unconstrain(w1[i0__]);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable w1: ") + e.what());
        }

        if (!(context__.contains_r("w2")))
            throw std::runtime_error("variable w2 missing");
        vals_r__ = context__.vals_r("w2");
        pos__ = 0U;
        validate_non_negative_index("w2", "Nsubj_tg", Nsubj_tg);
        context__.validate_dims("initialization", "w2", "double", context__.to_vec(Nsubj_tg));
        std::vector<double> w2(Nsubj_tg,double(0));
        for (int i0__ = 0U; i0__ < Nsubj_tg; ++i0__)
            w2[i0__] = vals_r__[pos__++];
        for (int i0__ = 0U; i0__ < Nsubj_tg; ++i0__)
            try {
            writer__.scalar_ub_unconstrain(0,w2[i0__]);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable w2: ") + e.what());
        }

        if (!(context__.contains_r("w3")))
            throw std::runtime_error("variable w3 missing");
        vals_r__ = context__.vals_r("w3");
        pos__ = 0U;
        validate_non_negative_index("w3", "Nsubj", Nsubj);
        context__.validate_dims("initialization", "w3", "double", context__.to_vec(Nsubj));
        std::vector<double> w3(Nsubj,double(0));
        for (int i0__ = 0U; i0__ < Nsubj; ++i0__)
            w3[i0__] = vals_r__[pos__++];
        for (int i0__ = 0U; i0__ < Nsubj; ++i0__)
            try {
            writer__.scalar_lb_unconstrain(0,w3[i0__]);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable w3: ") + e.what());
        }

        if (!(context__.contains_r("delta")))
            throw std::runtime_error("variable delta missing");
        vals_r__ = context__.vals_r("delta");
        pos__ = 0U;
        validate_non_negative_index("delta", "Nsubj_sg", Nsubj_sg);
        context__.validate_dims("initialization", "delta", "double", context__.to_vec(Nsubj_sg));
        std::vector<double> delta(Nsubj_sg,double(0));
        for (int i0__ = 0U; i0__ < Nsubj_sg; ++i0__)
            delta[i0__] = vals_r__[pos__++];
        for (int i0__ = 0U; i0__ < Nsubj_sg; ++i0__)
            try {
            writer__.scalar_lub_unconstrain(0.20000000000000001,1,delta[i0__]);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable delta: ") + e.what());
        }

        if (!(context__.contains_r("tau")))
            throw std::runtime_error("variable tau missing");
        vals_r__ = context__.vals_r("tau");
        pos__ = 0U;
        validate_non_negative_index("tau", "Nsubj_tg", Nsubj_tg);
        context__.validate_dims("initialization", "tau", "double", context__.to_vec(Nsubj_tg));
        std::vector<double> tau(Nsubj_tg,double(0));
        for (int i0__ = 0U; i0__ < Nsubj_tg; ++i0__)
            tau[i0__] = vals_r__[pos__++];
        for (int i0__ = 0U; i0__ < Nsubj_tg; ++i0__)
            try {
            writer__.scalar_lub_unconstrain(0.20000000000000001,1,tau[i0__]);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable tau: ") + e.what());
        }

        if (!(context__.contains_r("alpha")))
            throw std::runtime_error("variable alpha missing");
        vals_r__ = context__.vals_r("alpha");
        pos__ = 0U;
        validate_non_negative_index("alpha", "Nsubj", Nsubj);
        context__.validate_dims("initialization", "alpha", "double", context__.to_vec(Nsubj));
        std::vector<double> alpha(Nsubj,double(0));
        for (int i0__ = 0U; i0__ < Nsubj; ++i0__)
            alpha[i0__] = vals_r__[pos__++];
        for (int i0__ = 0U; i0__ < Nsubj; ++i0__)
            try {
            writer__.scalar_lub_unconstrain(0.01,0.98999999999999999,alpha[i0__]);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable alpha: ") + e.what());
        }

        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }


    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(vector<T__>& params_r__,
                 vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {

        typedef T__ local_scalar_t__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;

        try {
            // model parameters
            stan::io::reader<local_scalar_t__> in__(params_r__,params_i__);

            vector<local_scalar_t__> w1;
            size_t dim_w1_0__ = Nsubj_sg;
            w1.reserve(dim_w1_0__);
            for (size_t k_0__ = 0; k_0__ < dim_w1_0__; ++k_0__) {
                if (jacobian__)
                    w1.push_back(in__.scalar_constrain(lp__));
                else
                    w1.push_back(in__.scalar_constrain());
            }

            vector<local_scalar_t__> w2;
            size_t dim_w2_0__ = Nsubj_tg;
            w2.reserve(dim_w2_0__);
            for (size_t k_0__ = 0; k_0__ < dim_w2_0__; ++k_0__) {
                if (jacobian__)
                    w2.push_back(in__.scalar_ub_constrain(0,lp__));
                else
                    w2.push_back(in__.scalar_ub_constrain(0));
            }

            vector<local_scalar_t__> w3;
            size_t dim_w3_0__ = Nsubj;
            w3.reserve(dim_w3_0__);
            for (size_t k_0__ = 0; k_0__ < dim_w3_0__; ++k_0__) {
                if (jacobian__)
                    w3.push_back(in__.scalar_lb_constrain(0,lp__));
                else
                    w3.push_back(in__.scalar_lb_constrain(0));
            }

            vector<local_scalar_t__> delta;
            size_t dim_delta_0__ = Nsubj_sg;
            delta.reserve(dim_delta_0__);
            for (size_t k_0__ = 0; k_0__ < dim_delta_0__; ++k_0__) {
                if (jacobian__)
                    delta.push_back(in__.scalar_lub_constrain(0.20000000000000001,1,lp__));
                else
                    delta.push_back(in__.scalar_lub_constrain(0.20000000000000001,1));
            }

            vector<local_scalar_t__> tau;
            size_t dim_tau_0__ = Nsubj_tg;
            tau.reserve(dim_tau_0__);
            for (size_t k_0__ = 0; k_0__ < dim_tau_0__; ++k_0__) {
                if (jacobian__)
                    tau.push_back(in__.scalar_lub_constrain(0.20000000000000001,1,lp__));
                else
                    tau.push_back(in__.scalar_lub_constrain(0.20000000000000001,1));
            }

            vector<local_scalar_t__> alpha;
            size_t dim_alpha_0__ = Nsubj;
            alpha.reserve(dim_alpha_0__);
            for (size_t k_0__ = 0; k_0__ < dim_alpha_0__; ++k_0__) {
                if (jacobian__)
                    alpha.push_back(in__.scalar_lub_constrain(0.01,0.98999999999999999,lp__));
                else
                    alpha.push_back(in__.scalar_lub_constrain(0.01,0.98999999999999999));
            }


            // transformed parameters
            current_statement_begin__ = 96;
            validate_non_negative_index("phi", "1", 1);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  phi(static_cast<Eigen::VectorXd::Index>(1));
            (void) phi;  // dummy to suppress unused var warning

            stan::math::initialize(phi, DUMMY_VAR__);
            stan::math::fill(phi,DUMMY_VAR__);
            current_statement_begin__ = 97;
            validate_non_negative_index("theta", "6", 6);
            validate_non_negative_index("theta", "Nsubj", Nsubj);
            vector<Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1> > theta(Nsubj, (Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1> (static_cast<Eigen::VectorXd::Index>(6))));
            stan::math::initialize(theta, DUMMY_VAR__);
            stan::math::fill(theta,DUMMY_VAR__);


            current_statement_begin__ = 99;
            stan::model::assign(phi, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                        1, 
                        "assigning variable phi");
            current_statement_begin__ = 101;
            for (int subj = 1; subj <= Nsubj; ++subj) {

                current_statement_begin__ = 103;
                if (as_bool(logical_eq(get_base1(expt,subj,"expt",1),1))) {

                    current_statement_begin__ = 104;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list())), 
                                get_base1(w1,get_base1(s_sg,subj,"s_sg",1),"w1",1), 
                                "assigning variable theta");
                    current_statement_begin__ = 105;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list())), 
                                0, 
                                "assigning variable theta");
                    current_statement_begin__ = 106;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list())), 
                                get_base1(w3,subj,"w3",1), 
                                "assigning variable theta");
                    current_statement_begin__ = 107;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(4), stan::model::nil_index_list())), 
                                get_base1(delta,get_base1(s_sg,subj,"s_sg",1),"delta",1), 
                                "assigning variable theta");
                    current_statement_begin__ = 108;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(5), stan::model::nil_index_list())), 
                                0, 
                                "assigning variable theta");
                    current_statement_begin__ = 109;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(6), stan::model::nil_index_list())), 
                                get_base1(alpha,subj,"alpha",1), 
                                "assigning variable theta");
                }
                current_statement_begin__ = 112;
                if (as_bool(logical_eq(get_base1(expt,subj,"expt",1),2))) {

                    current_statement_begin__ = 113;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list())), 
                                0, 
                                "assigning variable theta");
                    current_statement_begin__ = 114;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list())), 
                                get_base1(w2,get_base1(s_tg,subj,"s_tg",1),"w2",1), 
                                "assigning variable theta");
                    current_statement_begin__ = 115;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list())), 
                                get_base1(w3,subj,"w3",1), 
                                "assigning variable theta");
                    current_statement_begin__ = 116;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(4), stan::model::nil_index_list())), 
                                0, 
                                "assigning variable theta");
                    current_statement_begin__ = 117;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(5), stan::model::nil_index_list())), 
                                get_base1(tau,get_base1(s_tg,subj,"s_tg",1),"tau",1), 
                                "assigning variable theta");
                    current_statement_begin__ = 118;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(6), stan::model::nil_index_list())), 
                                get_base1(alpha,subj,"alpha",1), 
                                "assigning variable theta");
                }
                current_statement_begin__ = 121;
                if (as_bool(logical_eq(get_base1(expt,subj,"expt",1),3))) {

                    current_statement_begin__ = 122;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list())), 
                                get_base1(w1,get_base1(s_sg,subj,"s_sg",1),"w1",1), 
                                "assigning variable theta");
                    current_statement_begin__ = 123;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list())), 
                                get_base1(w2,get_base1(s_tg,subj,"s_tg",1),"w2",1), 
                                "assigning variable theta");
                    current_statement_begin__ = 124;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list())), 
                                get_base1(w3,subj,"w3",1), 
                                "assigning variable theta");
                    current_statement_begin__ = 125;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(4), stan::model::nil_index_list())), 
                                get_base1(delta,get_base1(s_sg,subj,"s_sg",1),"delta",1), 
                                "assigning variable theta");
                    current_statement_begin__ = 126;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(5), stan::model::nil_index_list())), 
                                get_base1(tau,get_base1(s_tg,subj,"s_tg",1),"tau",1), 
                                "assigning variable theta");
                    current_statement_begin__ = 127;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(6), stan::model::nil_index_list())), 
                                get_base1(alpha,subj,"alpha",1), 
                                "assigning variable theta");
                }
            }

            // validate transformed parameters
            for (int i0__ = 0; i0__ < 1; ++i0__) {
                if (stan::math::is_uninitialized(phi(i0__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: phi" << '[' << i0__ << ']';
                    throw std::runtime_error(msg__.str());
                }
            }
            for (int i0__ = 0; i0__ < Nsubj; ++i0__) {
                for (int i1__ = 0; i1__ < 6; ++i1__) {
                    if (stan::math::is_uninitialized(theta[i0__](i1__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: theta" << '[' << i0__ << ']' << '[' << i1__ << ']';
                        throw std::runtime_error(msg__.str());
                    }
                }
            }

            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 96;
            current_statement_begin__ = 97;

            // model body

            current_statement_begin__ = 135;
            lp_accum__.add(normal_log<propto__>(w1, 0, 5));
            current_statement_begin__ = 136;
            lp_accum__.add(normal_log<propto__>(w2, 0, 5));
            current_statement_begin__ = 137;
            lp_accum__.add(normal_log<propto__>(w3, 0, 5));
            current_statement_begin__ = 139;
            lp_accum__.add(sum(map_rect<1, goal_sub_functor__>(phi, theta, real_data, int_data, pstream__)));

        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        lp_accum__.add(lp__);
        return lp_accum__.sum();

    } // log_prob()

    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }


    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("w1");
        names__.push_back("w2");
        names__.push_back("w3");
        names__.push_back("delta");
        names__.push_back("tau");
        names__.push_back("alpha");
        names__.push_back("phi");
        names__.push_back("theta");
    }


    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(Nsubj_sg);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Nsubj_tg);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Nsubj);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Nsubj_sg);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Nsubj_tg);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Nsubj);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(1);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Nsubj);
        dims__.push_back(6);
        dimss__.push_back(dims__);
    }

    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;

        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__,params_i__);
        static const char* function__ = "goal_fixed_space_expt123_bndshape_mpi_model_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        vector<double> w1;
        size_t dim_w1_0__ = Nsubj_sg;
        for (size_t k_0__ = 0; k_0__ < dim_w1_0__; ++k_0__) {
            w1.push_back(in__.scalar_constrain());
        }
        vector<double> w2;
        size_t dim_w2_0__ = Nsubj_tg;
        for (size_t k_0__ = 0; k_0__ < dim_w2_0__; ++k_0__) {
            w2.push_back(in__.scalar_ub_constrain(0));
        }
        vector<double> w3;
        size_t dim_w3_0__ = Nsubj;
        for (size_t k_0__ = 0; k_0__ < dim_w3_0__; ++k_0__) {
            w3.push_back(in__.scalar_lb_constrain(0));
        }
        vector<double> delta;
        size_t dim_delta_0__ = Nsubj_sg;
        for (size_t k_0__ = 0; k_0__ < dim_delta_0__; ++k_0__) {
            delta.push_back(in__.scalar_lub_constrain(0.20000000000000001,1));
        }
        vector<double> tau;
        size_t dim_tau_0__ = Nsubj_tg;
        for (size_t k_0__ = 0; k_0__ < dim_tau_0__; ++k_0__) {
            tau.push_back(in__.scalar_lub_constrain(0.20000000000000001,1));
        }
        vector<double> alpha;
        size_t dim_alpha_0__ = Nsubj;
        for (size_t k_0__ = 0; k_0__ < dim_alpha_0__; ++k_0__) {
            alpha.push_back(in__.scalar_lub_constrain(0.01,0.98999999999999999));
        }
            for (int k_0__ = 0; k_0__ < Nsubj_sg; ++k_0__) {
            vars__.push_back(w1[k_0__]);
            }
            for (int k_0__ = 0; k_0__ < Nsubj_tg; ++k_0__) {
            vars__.push_back(w2[k_0__]);
            }
            for (int k_0__ = 0; k_0__ < Nsubj; ++k_0__) {
            vars__.push_back(w3[k_0__]);
            }
            for (int k_0__ = 0; k_0__ < Nsubj_sg; ++k_0__) {
            vars__.push_back(delta[k_0__]);
            }
            for (int k_0__ = 0; k_0__ < Nsubj_tg; ++k_0__) {
            vars__.push_back(tau[k_0__]);
            }
            for (int k_0__ = 0; k_0__ < Nsubj; ++k_0__) {
            vars__.push_back(alpha[k_0__]);
            }

        // declare and define transformed parameters
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        try {
            current_statement_begin__ = 96;
            validate_non_negative_index("phi", "1", 1);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  phi(static_cast<Eigen::VectorXd::Index>(1));
            (void) phi;  // dummy to suppress unused var warning

            stan::math::initialize(phi, DUMMY_VAR__);
            stan::math::fill(phi,DUMMY_VAR__);
            current_statement_begin__ = 97;
            validate_non_negative_index("theta", "6", 6);
            validate_non_negative_index("theta", "Nsubj", Nsubj);
            vector<Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1> > theta(Nsubj, (Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1> (static_cast<Eigen::VectorXd::Index>(6))));
            stan::math::initialize(theta, DUMMY_VAR__);
            stan::math::fill(theta,DUMMY_VAR__);


            current_statement_begin__ = 99;
            stan::model::assign(phi, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                        1, 
                        "assigning variable phi");
            current_statement_begin__ = 101;
            for (int subj = 1; subj <= Nsubj; ++subj) {

                current_statement_begin__ = 103;
                if (as_bool(logical_eq(get_base1(expt,subj,"expt",1),1))) {

                    current_statement_begin__ = 104;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list())), 
                                get_base1(w1,get_base1(s_sg,subj,"s_sg",1),"w1",1), 
                                "assigning variable theta");
                    current_statement_begin__ = 105;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list())), 
                                0, 
                                "assigning variable theta");
                    current_statement_begin__ = 106;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list())), 
                                get_base1(w3,subj,"w3",1), 
                                "assigning variable theta");
                    current_statement_begin__ = 107;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(4), stan::model::nil_index_list())), 
                                get_base1(delta,get_base1(s_sg,subj,"s_sg",1),"delta",1), 
                                "assigning variable theta");
                    current_statement_begin__ = 108;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(5), stan::model::nil_index_list())), 
                                0, 
                                "assigning variable theta");
                    current_statement_begin__ = 109;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(6), stan::model::nil_index_list())), 
                                get_base1(alpha,subj,"alpha",1), 
                                "assigning variable theta");
                }
                current_statement_begin__ = 112;
                if (as_bool(logical_eq(get_base1(expt,subj,"expt",1),2))) {

                    current_statement_begin__ = 113;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list())), 
                                0, 
                                "assigning variable theta");
                    current_statement_begin__ = 114;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list())), 
                                get_base1(w2,get_base1(s_tg,subj,"s_tg",1),"w2",1), 
                                "assigning variable theta");
                    current_statement_begin__ = 115;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list())), 
                                get_base1(w3,subj,"w3",1), 
                                "assigning variable theta");
                    current_statement_begin__ = 116;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(4), stan::model::nil_index_list())), 
                                0, 
                                "assigning variable theta");
                    current_statement_begin__ = 117;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(5), stan::model::nil_index_list())), 
                                get_base1(tau,get_base1(s_tg,subj,"s_tg",1),"tau",1), 
                                "assigning variable theta");
                    current_statement_begin__ = 118;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(6), stan::model::nil_index_list())), 
                                get_base1(alpha,subj,"alpha",1), 
                                "assigning variable theta");
                }
                current_statement_begin__ = 121;
                if (as_bool(logical_eq(get_base1(expt,subj,"expt",1),3))) {

                    current_statement_begin__ = 122;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list())), 
                                get_base1(w1,get_base1(s_sg,subj,"s_sg",1),"w1",1), 
                                "assigning variable theta");
                    current_statement_begin__ = 123;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list())), 
                                get_base1(w2,get_base1(s_tg,subj,"s_tg",1),"w2",1), 
                                "assigning variable theta");
                    current_statement_begin__ = 124;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list())), 
                                get_base1(w3,subj,"w3",1), 
                                "assigning variable theta");
                    current_statement_begin__ = 125;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(4), stan::model::nil_index_list())), 
                                get_base1(delta,get_base1(s_sg,subj,"s_sg",1),"delta",1), 
                                "assigning variable theta");
                    current_statement_begin__ = 126;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(5), stan::model::nil_index_list())), 
                                get_base1(tau,get_base1(s_tg,subj,"s_tg",1),"tau",1), 
                                "assigning variable theta");
                    current_statement_begin__ = 127;
                    stan::model::assign(theta, 
                                stan::model::cons_list(stan::model::index_uni(subj), stan::model::cons_list(stan::model::index_uni(6), stan::model::nil_index_list())), 
                                get_base1(alpha,subj,"alpha",1), 
                                "assigning variable theta");
                }
            }

            // validate transformed parameters
            current_statement_begin__ = 96;
            current_statement_begin__ = 97;

            // write transformed parameters
            if (include_tparams__) {
            for (int k_0__ = 0; k_0__ < 1; ++k_0__) {
            vars__.push_back(phi[k_0__]);
            }
            for (int k_1__ = 0; k_1__ < 6; ++k_1__) {
                for (int k_0__ = 0; k_0__ < Nsubj; ++k_0__) {
                vars__.push_back(theta[k_0__][k_1__]);
                }
            }
            }
            if (!include_gqs__) return;
            // declare and define generated quantities



            // validate generated quantities

            // write generated quantities
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng,params_r_vec,params_i_vec,vars_vec,include_tparams,include_gqs,pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    static std::string model_name() {
        return "goal_fixed_space_expt123_bndshape_mpi_model";
    }


    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        for (int k_0__ = 1; k_0__ <= Nsubj_sg; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "w1" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= Nsubj_tg; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "w2" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= Nsubj; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "w3" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= Nsubj_sg; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "delta" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= Nsubj_tg; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "tau" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= Nsubj; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "alpha" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
            for (int k_0__ = 1; k_0__ <= 1; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "phi" << '.' << k_0__;
                param_names__.push_back(param_name_stream__.str());
            }
            for (int k_1__ = 1; k_1__ <= 6; ++k_1__) {
                for (int k_0__ = 1; k_0__ <= Nsubj; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "theta" << '.' << k_0__ << '.' << k_1__;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }


        if (!include_gqs__) return;
    }


    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        for (int k_0__ = 1; k_0__ <= Nsubj_sg; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "w1" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= Nsubj_tg; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "w2" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= Nsubj; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "w3" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= Nsubj_sg; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "delta" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= Nsubj_tg; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "tau" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= Nsubj; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "alpha" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
            for (int k_0__ = 1; k_0__ <= 1; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "phi" << '.' << k_0__;
                param_names__.push_back(param_name_stream__.str());
            }
            for (int k_1__ = 1; k_1__ <= 6; ++k_1__) {
                for (int k_0__ = 1; k_0__ <= Nsubj; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "theta" << '.' << k_0__ << '.' << k_1__;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }


        if (!include_gqs__) return;
    }

}; // model

}

typedef goal_fixed_space_expt123_bndshape_mpi_model_namespace::goal_fixed_space_expt123_bndshape_mpi_model stan_model;

STAN_REGISTER_MAP_RECT(1, goal_fixed_space_expt123_bndshape_mpi_model_namespace::goal_sub_functor__)
